---
title: "Publications"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    graphics: yes
---

```{r setup, include=FALSE}
library(flexdashboard)
library(scholar)
library(knitr)
library(ggplot2)
library(cowplot)
library(tidyverse)
library(kableExtra)
library(emojifont)
library(wordcloud2)
```

```{r theme-set, include=FALSE}
theme_set(theme_cowplot(font_size=7))
```

```{r valuebox,  include=FALSE}
createValueBoxes <- function(df, h = 2, w = 5, padding=0.5, rows = 2){
  # required packages
  
  
  # verify our inputs
  if (!is.data.frame(df)) {
    stop(paste("Argument", deparse(substitute(df)), "must be a data.frame."))
    }
  if(!all(i <- rlang::has_name(df,c("values", "infos", "icons")))){
    stop(sprintf(
      "%s does not contain: %s",
      deparse(substitute(df)),
      paste(columns[!i], collapse=", ")))
  }
  
  boxes = nrow(df) # number of items passed
  # calculate the grid
  cols = boxes/rows
  plotdf <- data.frame(
    x = rep(seq(0, (w+padding)*cols-1, w+padding), times=rows),
    y = rep(seq(0, (h+padding)*rows-1, h+padding), each=cols),
    h = rep(h, boxes),
    w = rep(w, boxes),
    value = df$values,
    info = df$infos,
    icon = fontawesome(df$icons),
    font_family = c(rep("fontawesome-webfont", boxes)),
    color = factor(1:boxes)
  )
  #print(plotdf)
  ggplot(plotdf, aes(x, y, height = h, width = w, label = info)) +
    ## Create the tiles using the `color` column
    geom_tile(aes(fill = color)) +
    ## Add the numeric values as text in `value` column
    geom_text(color = "white", fontface = "bold", size = 8,
              aes(label = value, x = x - w/2.2, y = y + h/4), hjust = 0) +
    ## Add the labels for each box stored in the `info` column
    geom_text(color = "white", fontface = "bold",
              aes(label = info, x = x - w/2.2, y = y-h/4), hjust = 0) +
    coord_fixed() +
    scale_fill_brewer(type = "qual",palette = "Dark2") +
    ## Use `geom_text()` to add the icons by specifying the unicode symbol.
    geom_text(size = 12, aes(label = icon, family = font_family,
                             x = x + w/4, y = y + h/8), alpha = 0.25) +
    theme_void() +
    guides(fill = "none")
  
} 
```

```{r scholar, include=FALSE}
#Define the person to analyze
scholar_id=c("sH4_TPkAAAAJ","59ha_gEAAAAJ","KtFmcBIAAAAJ")
#either load existing file of publications
#or get a new one from Google Scholar
#delete the file to force an update
#get citations
cites<-list()
num_articles<-list()
papers<-list()
auth.profile<-list()

for (i in scholar_id){
cites[[i]] <- scholar::get_citation_history(i) 
num_articles[[i]]<-scholar::get_num_articles(i)
papers[[i]]<-scholar::get_publications(i)
auth.profile[[i]]<-scholar::get_profile(i)
}

cites.total <- scholar::get_citation_history(scholar_id[1]) 
num_articles.total<-scholar::get_num_articles(scholar_id[1])
papers.total<-scholar::get_publications(scholar_id[1])


#saveRDS(cites,'citations.Rds')

# manual curation
auth.profile[[2]]$name<-"Mohammed Errbii"

```

```{r plot-valuebox, fig.height=1.5, fig.width=4, message=FALSE, warning=FALSE, echo=FALSE}
df<-data.frame(values=c(num_articles.total,sum(cites.total$cites)),infos=c("Publications","Citations"),icons=c("fa-file", "fa-book"))
#createValueBoxes(df, rows=1)

```

 {.tabset}
-----------------------------
```{r publications-functions, include=FALSE}

paperPlots <- function(author.number) {
  p1<-ggplot(cites[[author.number]],aes(x=as.factor(year),y=cites))+
    geom_bar(stat="identity",fill="steelblue")+
    xlab(NULL)+ylab("# citations")+
    theme(axis.text.x = element_text(angle = -45, vjust = 0.5, hjust=0.1))
  
  
  pap.year<-plyr::count(papers[[author.number]]$year)
  p2<-ggplot(pap.year,aes(x=as.factor(x),y=freq),fill="black")+
    geom_bar(stat="identity",fill="steelblue")+
    xlab(NULL)+ylab("# publications")+
    theme(axis.text.x = element_text(angle = -45, vjust = 0.5, hjust=0.1))
  plot_grid(p1,p2,nrow=1)
}

paperTab <- function(author.number) {
  paperTable<-papers[[author.number]][order(papers[[author.number]]$year,decreasing = T),c(1,2,3,6)]
  colnames(paperTable)<-c("Title","Authors","Journal","Year")
  kbl(paperTable, caption = paste(nrow(paperTable)," publications (co-)authored by ", auth.profile[[author.number]]$name," as of ", format(Sys.time(), "%b %d %Y")," ([google scholar](https://scholar.google.de/citations?user=",scholar_id[author.number],"))",sep=""),row.names = F) %>% kable_styling(bootstrap_options = c("striped", "hover"))
}

```


### `r author.number<-1; auth.profile[[author.number]]$name`
#### 

```{r fig.height=1.5, fig.width=4, message=FALSE, warning=FALSE, echo=FALSE}
paperPlots(author.number)
```

####
<div class="publication">
```{r, message=FALSE, warning=FALSE, echo=FALSE}
paperTab(author.number)
```
</div>


### `r author.number<-2; auth.profile[[author.number]]$name`
#### 
```{r fig.height=1.5, fig.width=4, message=FALSE, warning=FALSE, echo=FALSE}
paperPlots(author.number)
```


####
<div class="publication">
```{r, message=FALSE, warning=FALSE, echo=FALSE}
paperTab(author.number)
```
</div>

### `r author.number<-3; auth.profile[[author.number]]$name`
#### 
```{r fig.height=1.5, fig.width=4, message=FALSE, warning=FALSE, echo=FALSE}
paperPlots(author.number)
```


####
<div class="publication">
```{r, message=FALSE, warning=FALSE, echo=FALSE}
paperTab(author.number)
```
</div>